[alembic]
script_location = alembic
sqlalchemy.url = postgresql+asyncpg://cyclecoach:cyclecoach@localhost:5432/cyclecoach

[loggers]
keys = root
[handlers]
keys = console
[logger_root]
level = WARN
handlers = console
